name: op3n-unified-framework automation

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'Give input for specific tests selection'
        required: true
        default: 'testng_API'
        options:
          - 'hai'
          - 'hello'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - run: echo "${{ github.event.inputs.user_input}}"
