name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: 'Give input for specific tests selection'
        required: true
        options:
          - 'testng_API'
          - 'testng_v2_Web'

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.name }}"
